#!/usr/bin/env python3
"""
make_systematic_latex_table.py

Reads the STEP 6 text-dump output of plot_ESE_systematics.C
(text_output/systematic_uncertainty_v{2,3}.txt -- Slope and Intercept only; Pearson r is not
in this table since its systematic uses a different, MC-based method) and writes one LaTeX
longtable per harmonic, ready to paste into Overleaf: one row per (Quantity, Centrality, pT)
bin, one column-pair (Abs | Rel%) per systematic source (the "Adopted" value -- whichever
variation deviates more from nominal, for a two-variation source), plus a final Total column-pair.

Source order and labels are read directly from the source_label[] line the macro itself keeps
in sync with -- see SOURCE_LABELS below; update it here if the macro's N_SOURCES/source_label[]
ever changes.

Usage:
    python3 make_systematic_latex_table.py <outbase>
e.g.
    python3 make_systematic_latex_table.py ESE_systematics_20260916

Writes <outbase>/text_output/systematic_table_v2.tex and systematic_table_v3.tex.
"""
import sys
import os

SOURCE_LABELS = ["SigPDF", "BkgPDF", "BDT", "Centrality", "qn quantile", "PromptFraction", "Syst7"]
N_SOURCES = len(SOURCE_LABELS)

# 5 fixed leading tokens (Cent, pT, Nominal, StatLo, StatHi), then 6 tokens per source
# (VarA_abs, VarA_rel, VarB_abs, VarB_rel, Adopted_abs, Adopted_rel), then 2 trailing tokens
# (TotalSyst_abs, TotalSyst_rel) -- see plot_ESE_systematics.C's STEP 6 fprintf layout.
N_LEAD = 5
N_PER_SRC = 6
N_TRAIL = 2


def tex_escape(s):
    return s.replace("_", r"\_").replace("%", r"\%")


def fmt_abs(tok):
    try:
        return f"{float(tok):.3f}"
    except ValueError:
        return "--"


def fmt_rel(tok):
    tok = tok.rstrip("*")
    try:
        return f"{float(tok):.1f}"
    except ValueError:
        return "--"


def parse_quantity_block(lines):
    """lines: data rows (post-header) for one 'Quantity: ...' block, up to the next blank
    line. Returns a list of dicts: {cent, pt, sources: [(abs,rel)]*N_SOURCES, total: (abs,rel)}."""
    rows = []
    for line in lines:
        line = line.rstrip("\n")
        if not line.strip():
            break
        tok = line.split()
        if len(tok) != N_LEAD + N_PER_SRC * N_SOURCES + N_TRAIL:
            continue  # not a data row (shouldn't happen once we're past the header)
        cent = tok[0]
        pt = tok[1]
        srcs = []
        pos = N_LEAD
        for _ in range(N_SOURCES):
            adopted_abs = tok[pos + 4]
            adopted_rel = tok[pos + 5]
            srcs.append((adopted_abs, adopted_rel))
            pos += N_PER_SRC
        total_abs = tok[pos]
        total_rel = tok[pos + 1]
        rows.append({"cent": cent, "pt": pt, "sources": srcs, "total": (total_abs, total_rel)})
    return rows


def parse_file(path):
    """Returns {'Slope': [rows...], 'Intercept': [rows...]}."""
    with open(path) as f:
        lines = f.readlines()

    blocks = {}
    i = 0
    while i < len(lines):
        if lines[i].startswith("Quantity:"):
            qname = lines[i].split("Quantity:")[1].strip()
            # Skip the "====" line and the column-header line that follow.
            i += 3
            blocks[qname] = parse_quantity_block(lines[i:])
        i += 1
    return blocks


CENT_DISPLAY = {
    "cent0to10": "0--10\\%", "cent10to20": "10--20\\%", "cent20to30": "20--30\\%",
    "cent30to40": "30--40\\%", "cent40to50": "40--50\\%",
}


def write_latex(blocks, ivn, outpath):
    ncols = 2 + 2 * N_SOURCES + 2  # Cent, pT, (abs,rel)*sources, (abs,rel)Total
    colspec = "ll" + "rr" * N_SOURCES + "rr"

    with open(outpath, "w") as f:
        f.write("% Auto-generated by make_systematic_latex_table.py -- do not edit by hand;\n")
        f.write("% regenerate after rerunning plot_ESE_systematics.C's STEP 6 text dump.\n")
        f.write("% Requires: \\usepackage{longtable}, \\usepackage{pdflscape} (or rotating),\n")
        f.write("%           \\usepackage{booktabs} (for \\toprule/\\midrule/\\bottomrule).\n")
        f.write("\\begin{landscape}\n")
        f.write("\\scriptsize\n")
        f.write("\\setlength{\\tabcolsep}{2.5pt}\n")
        f.write(f"\\begin{{longtable}}{{{colspec}}}\n")
        f.write(f"\\caption{{Systematic uncertainty on the D0-vs-charged-particle Slope and "
                f"Intercept ($v_{{{ivn}}}$), from each source (Adopted value: whichever "
                f"variation deviates more from nominal for a two-variation source) and their "
                f"quadratic-sum Total, per centrality and $p_{{\\rm T}}$ bin. Abs.\\ is the "
                f"absolute shift from nominal; Rel.\\ is that shift as a percentage of the "
                f"nominal value (`--' where the nominal value is below the omission threshold "
                f"or the source has no valid point in that bin).}}\n")
        f.write(f"\\label{{tab:syst_v{ivn}}}\\\\\n")
        f.write("\\toprule\n")

        header1 = ["", ""] + [f"\\multicolumn{{2}}{{c}}{{{tex_escape(s)}}}" for s in SOURCE_LABELS] + \
                  ["\\multicolumn{2}{c}{Total}"]
        header2 = ["Cent", "$p_{\\rm T}$ (GeV/c)"] + ["Abs.", "Rel.(\\%)"] * N_SOURCES + ["Abs.", "Rel.(\\%)"]
        f.write(" & ".join(header1) + " \\\\\n")
        f.write(" & ".join(header2) + " \\\\\n")
        f.write("\\midrule\n")
        f.write("\\endfirsthead\n")
        f.write(f"\\multicolumn{{{ncols}}}{{l}}{{\\small\\itshape (continued from previous page)}}\\\\\n")
        f.write("\\toprule\n")
        f.write(" & ".join(header1) + " \\\\\n")
        f.write(" & ".join(header2) + " \\\\\n")
        f.write("\\midrule\n")
        f.write("\\endhead\n")
        f.write("\\midrule\n")
        f.write(f"\\multicolumn{{{ncols}}}{{r}}{{\\small\\itshape (continued on next page)}}\\\\\n")
        f.write("\\endfoot\n")
        f.write("\\bottomrule\n")
        f.write("\\endlastfoot\n")

        for qname in ("Slope", "Intercept"):
            if qname not in blocks:
                continue
            f.write(f"\\multicolumn{{{ncols}}}{{l}}{{\\textbf{{{qname}}}}} \\\\\n")
            f.write("\\midrule\n")
            for row in blocks[qname]:
                cent_disp = CENT_DISPLAY.get(row["cent"], tex_escape(row["cent"]))
                cells = [cent_disp, row["pt"]]
                for (a, r) in row["sources"]:
                    cells.append(fmt_abs(a))
                    cells.append(fmt_rel(r))
                cells.append(fmt_abs(row["total"][0]))
                cells.append(fmt_rel(row["total"][1]))
                f.write(" & ".join(cells) + " \\\\\n")
            f.write("\\midrule\n")

        f.write("\\end{longtable}\n")
        f.write("\\end{landscape}\n")


def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <outbase>", file=sys.stderr)
        sys.exit(1)
    outbase = sys.argv[1]
    for ivn in (2, 3):
        inpath = os.path.join(outbase, "text_output", f"systematic_uncertainty_v{ivn}.txt")
        if not os.path.isfile(inpath):
            print(f"WARNING: {inpath} not found -- skipped.", file=sys.stderr)
            continue
        blocks = parse_file(inpath)
        outpath = os.path.join(outbase, "text_output", f"systematic_table_v{ivn}.tex")
        write_latex(blocks, ivn, outpath)
        n_rows = sum(len(v) for v in blocks.values())
        print(f"Wrote {outpath}  ({n_rows} data rows)")


if __name__ == "__main__":
    main()
