#pragma once
#include <cmath>

// These headers are generated by the SP-binning pipeline and do not exist
// before save_vnbinning_to_txt.C + generate_vnbinning_header.C have been run.
// Define SKIP_VNBINNING_GENERATED (as save_vnbinning_to_txt.C does) to compile without them.
// fit_mass_and_flow.C must NOT define it — it needs both headers.

#ifndef SKIP_VNBINNING_GENERATED
#include "vnbinning_generated.h"       // SP bin edge arrays (auto-generated)
//#include "quantile_20Qbin_cuts_2023_MB0to31.h" // 20 quantile cut arrays
//#include "quantile_12NUQbin_cuts_2023_MB0to31.h" // 12 quantile cut arrays (NEW)
#include "quantile_12NUQbin_diffq2q3_cuts_2023_MB0to31.h"
#endif


// --- Mass distribution fit settings ---
const int N_MASSBINS = 48; //48 
Float_t fit_range_low = 1.75;
Float_t fit_range_high = 1.99;
Double_t D0_mass = 1.8648;
Float_t hist_range_low = 1.75;
Float_t hist_range_high = 1.99;
Float_t width = (hist_range_high-hist_range_low)/N_MASSBINS; //-->0.005

//--- Bin count constants ---
static const int N_QBINS      = 12;
static const int N_CENTBINS_1 = 50;
static const int N_CENTBINS   = 5;
static const int N_PTBINS     = 12; // legacy; kept for MC template indexing
static const int N_PTBINS_V2  = 9;  // v2 pT bins: 2,3,4,5,6,8,10,15,30,100
static const int N_PTBINS_V3  = 7;  // v3 pT bins: 2,4,6,8,10,20,50,100

  //const int N_PTBINS = 12;  
  
  
  const int N_BINS       = 2400;              // histogram bins for quantile search
  const int N_EDGES      = 11;                // quantile edges per side (incl. 0)

  const int N_SIDE_EDGES_V2 = 12;              // was N_SIDE_EDGES, for v2: 24 elements -> 12 per side
  const int N_SIDE_EDGES_V3 = 15;              // NEW: for v3: 30 elements -> 15 per side
  const int N_VBINS_V2    = (N_EDGES-1)*2 + (N_SIDE_EDGES_V2-1)*2;  // = 20+22 = 42
  const int N_VBINS_V3    = (N_EDGES-1)*2 + (N_SIDE_EDGES_V3-1)*2;  // = 20+28 = 48



// ---- Centrality bin definitions ---

static const int min_centbin[N_CENTBINS] = {0, 10, 20, 30, 40};
static const int max_centbin[N_CENTBINS] = {10, 20, 30, 40, 50};
static const int cen_edges[N_CENTBINS+1] = {0, 10, 20, 30, 40, 50};

static const char* cen_name[N_CENTBINS] = {
  "cent0to10", "cent10to20", "cent20to30", "cent30to40", "cent40to50"
};
TString cen_label[N_CENTBINS]={"cent0to10","cent10to20","cent20to30","cent30to40","cent40to50"};

static const char* centbin[N_CENTBINS] = {
    "0 <= cent < 10 %",  "10 <= cent < 20 %", "20 <= cent < 30 %",
    "30 <= cent < 40 %", "40 <= cent < 50 %"
};



// --- pT bin definitions (shared / legacy for MC template lookup) ----
static const double pt_edges[N_PTBINS+1] = {
    1, 2, 3, 4, 5, 6, 8, 10, 15, 20, 40, 60, 100
};
static const char* pt_name[N_PTBINS] = {
    "pT1to2",   "pT2to3",   "pT3to4",   "pT4to5",
    "pT5to6",   "pT6to8",   "pT8to10",  "pT10to15",
    "pT15to20", "pT20to40", "pT40to60", "pT60to100"
};
static const char* pTbin[N_PTBINS] = {
    "1.0 < pT < 2.0 GeV",   "2.0 < pT < 3.0 GeV",
    "3.0 < pT < 4.0 GeV",   "4.0 < pT < 5.0 GeV",
    "5.0 < pT < 6.0 GeV",   "6.0 < pT < 8.0 GeV",
    "8.0 < pT < 10.0 GeV",  "10.0 < pT < 15.0 GeV",
    "15.0 < pT < 20.0 GeV", "20.0 < pT < 40.0 GeV",
    "40.0 < pT < 60.0 GeV", "60.0 < pT < 100.0 GeV"
};

// --- v2 pT bin definitions: 2,3,4,5,6,8,10,15,30,100 (9 bins) ---
static const double pt_edges_v2[N_PTBINS_V2+1] = {
    2, 3, 4, 5, 6, 8, 10, 15, 30, 100
};
static const char* pt_name_v2[N_PTBINS_V2] = {
    "pT2to3",   "pT3to4",   "pT4to5",   "pT5to6",
    "pT6to8",   "pT8to10",  "pT10to15",
    "pT15to30", "pT30to100"
};
static const char* pTbin_v2[N_PTBINS_V2] = {
    "2.0 < pT < 3.0 GeV",   "3.0 < pT < 4.0 GeV",
    "4.0 < pT < 5.0 GeV",   "5.0 < pT < 6.0 GeV",
    "6.0 < pT < 8.0 GeV",   "8.0 < pT < 10.0 GeV",
    "10.0 < pT < 15.0 GeV", "15.0 < pT < 30.0 GeV",
    "30.0 < pT < 100.0 GeV"
};

// --- v3 pT bin definitions: 2,4,6,8,10,20,50,100 (7 bins) ---
static const double pt_edges_v3[N_PTBINS_V3+1] = {
    2, 4, 6, 8, 10, 20, 50, 100
};
static const char* pt_name_v3[N_PTBINS_V3] = {
    "pT2to4",  "pT4to6",  "pT6to8",
    "pT8to10", "pT10to20","pT20to50","pT50to100"
};
static const char* pTbin_v3[N_PTBINS_V3] = {
    "2.0 < pT < 4.0 GeV",   "4.0 < pT < 6.0 GeV",
    "6.0 < pT < 8.0 GeV",   "8.0 < pT < 10.0 GeV",
    "10.0 < pT < 20.0 GeV", "20.0 < pT < 50.0 GeV",
    "50.0 < pT < 100.0 GeV"
};

// --- vnbinning v2 lookup table [N_CENTBINS][N_PTBINS_V2] ----
#ifndef SKIP_VNBINNING_GENERATED
static const double* vnb_v2_table[N_CENTBINS][N_PTBINS_V2] = {
    // cent0to10
    { vnbinning_v2_cent0to10_pT2to3,
      vnbinning_v2_cent0to10_pT3to4,   vnbinning_v2_cent0to10_pT4to5,
      vnbinning_v2_cent0to10_pT5to6,   vnbinning_v2_cent0to10_pT6to8,
      vnbinning_v2_cent0to10_pT8to10,  vnbinning_v2_cent0to10_pT10to15,
      vnbinning_v2_cent0to10_pT15to30, vnbinning_v2_cent0to10_pT30to100 },
    // cent10to20
    { vnbinning_v2_cent10to20_pT2to3,
      vnbinning_v2_cent10to20_pT3to4,   vnbinning_v2_cent10to20_pT4to5,
      vnbinning_v2_cent10to20_pT5to6,   vnbinning_v2_cent10to20_pT6to8,
      vnbinning_v2_cent10to20_pT8to10,  vnbinning_v2_cent10to20_pT10to15,
      vnbinning_v2_cent10to20_pT15to30, vnbinning_v2_cent10to20_pT30to100 },
    // cent20to30
    { vnbinning_v2_cent20to30_pT2to3,
      vnbinning_v2_cent20to30_pT3to4,   vnbinning_v2_cent20to30_pT4to5,
      vnbinning_v2_cent20to30_pT5to6,   vnbinning_v2_cent20to30_pT6to8,
      vnbinning_v2_cent20to30_pT8to10,  vnbinning_v2_cent20to30_pT10to15,
      vnbinning_v2_cent20to30_pT15to30, vnbinning_v2_cent20to30_pT30to100 },
    // cent30to40
    { vnbinning_v2_cent30to40_pT2to3,
      vnbinning_v2_cent30to40_pT3to4,   vnbinning_v2_cent30to40_pT4to5,
      vnbinning_v2_cent30to40_pT5to6,   vnbinning_v2_cent30to40_pT6to8,
      vnbinning_v2_cent30to40_pT8to10,  vnbinning_v2_cent30to40_pT10to15,
      vnbinning_v2_cent30to40_pT15to30, vnbinning_v2_cent30to40_pT30to100 },
    // cent40to50
    { vnbinning_v2_cent40to50_pT2to3,
      vnbinning_v2_cent40to50_pT3to4,   vnbinning_v2_cent40to50_pT4to5,
      vnbinning_v2_cent40to50_pT5to6,   vnbinning_v2_cent40to50_pT6to8,
      vnbinning_v2_cent40to50_pT8to10,  vnbinning_v2_cent40to50_pT10to15,
      vnbinning_v2_cent40to50_pT15to30, vnbinning_v2_cent40to50_pT30to100 },
    // cent50to80
    /*{ vnbinning_v2_cent50to80_pT2to3,
      vnbinning_v2_cent50to80_pT3to4,   vnbinning_v2_cent50to80_pT4to5,
      vnbinning_v2_cent50to80_pT5to6,   vnbinning_v2_cent50to80_pT6to8,
      vnbinning_v2_cent50to80_pT8to10,  vnbinning_v2_cent50to80_pT10to15,
      vnbinning_v2_cent50to80_pT15to30, vnbinning_v2_cent50to80_pT30to100 }*/
};

//------ vnbinning v3 lookup table [N_CENTBINS][N_PTBINS_V3] -------

static const double* vnb_v3_table[N_CENTBINS][N_PTBINS_V3] = {
    // cent0to10
    { vnbinning_v3_cent0to10_pT2to4,
      vnbinning_v3_cent0to10_pT4to6,  vnbinning_v3_cent0to10_pT6to8,
      vnbinning_v3_cent0to10_pT8to10, vnbinning_v3_cent0to10_pT10to20,
      vnbinning_v3_cent0to10_pT20to50,vnbinning_v3_cent0to10_pT50to100 },
    // cent10to20
    { vnbinning_v3_cent10to20_pT2to4,
      vnbinning_v3_cent10to20_pT4to6,  vnbinning_v3_cent10to20_pT6to8,
      vnbinning_v3_cent10to20_pT8to10, vnbinning_v3_cent10to20_pT10to20,
      vnbinning_v3_cent10to20_pT20to50,vnbinning_v3_cent10to20_pT50to100 },
    // cent20to30
    { vnbinning_v3_cent20to30_pT2to4,
      vnbinning_v3_cent20to30_pT4to6,  vnbinning_v3_cent20to30_pT6to8,
      vnbinning_v3_cent20to30_pT8to10, vnbinning_v3_cent20to30_pT10to20,
      vnbinning_v3_cent20to30_pT20to50,vnbinning_v3_cent20to30_pT50to100 },
    // cent30to40
    { vnbinning_v3_cent30to40_pT2to4,
      vnbinning_v3_cent30to40_pT4to6,  vnbinning_v3_cent30to40_pT6to8,
      vnbinning_v3_cent30to40_pT8to10, vnbinning_v3_cent30to40_pT10to20,
      vnbinning_v3_cent30to40_pT20to50,vnbinning_v3_cent30to40_pT50to100 },
    // cent40to50
    { vnbinning_v3_cent40to50_pT2to4,
      vnbinning_v3_cent40to50_pT4to6,  vnbinning_v3_cent40to50_pT6to8,
      vnbinning_v3_cent40to50_pT8to10, vnbinning_v3_cent40to50_pT10to20,
      vnbinning_v3_cent40to50_pT20to50,vnbinning_v3_cent40to50_pT50to100 },
    // cent50to80
    /*{ vnbinning_v3_cent50to80_pT2to4,
      vnbinning_v3_cent50to80_pT4to6,  vnbinning_v3_cent50to80_pT6to8,
      vnbinning_v3_cent50to80_pT8to10, vnbinning_v3_cent50to80_pT10to20,
      vnbinning_v3_cent50to80_pT20to50,vnbinning_v3_cent50to80_pT50to100 }*/
};
#endif // SKIP_VNBINNING_GENERATED



inline double WeightedMeanError(TH1D* h)
{
    int n = h->GetNbinsX();
    double sumY = 0.0;
    for (int i = 1; i <= n; ++i) sumY += h->GetBinContent(i);
    if (sumY <= 0.0) return 0.0;

    double V = h->GetMean();  // weighted mean, computed internally
    double var = 0.0;
    for (int i = 1; i <= n; ++i) {
        double Yi  = h->GetBinContent(i);
        double dYi = h->GetBinError(i);
        double Vi  = h->GetBinCenter(i);
        double dVi = (Yi > 0) ? h->GetBinWidth(i) / std::sqrt(12.0 * Yi) : 0.0;
        double dV  = Vi - V;
        var += (dV * dV * dYi * dYi) + (Yi * Yi * dVi * dVi);
    }
    return std::sqrt(var / (sumY * sumY));
}
